current_dashboard: clock
flip_screen: false  # or true if you want the display upside-down
cycle:
  enabled: true
  interval_minutes: 5
  dashboards:
    clock: true
    youtube: false
    weather: true
    stocks: true
    text: false
    image: true
clock:
  invert_colors: false
  font_path: fonts/home-video-font/HomeVideo-BLG6G.ttf
  font_size: 50        # Font size for time
  date_font_size: 20   # Font size for date
  vertical_spacing: 16  # Pixels of space between time and date
  use_24hr: true
  show_date: true
  date_format: "%A, %b %d"
  # Examples:
  # date_format: "%b %d"        # Aug 01
  # date_format: "%A, %b %d"    # Thursday, Aug 01
  # date_format: "%Y-%m-%d"     # 2025-08-01"
  background: assets/Borders_and_Logos/250x122_Rounded_Frame_With_Shadow.bmp
  # background: assets/Borders_and_Logos/250x122_Geometric_Pattern.bmp
  # background: assets/Borders_and_Logos/250x122_Sqaure_With_Shadow_Background.bmp
  # background: null   # No background
  timezone: "America/Los_Angeles"
text:
  text: "Hello\nWorld!"
  font_path: /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
  font_size: 40
  vertical_spacing: 10
  invert_colors: false
  align: center  # options: left, center, right
  vertical_align: center #options: top, center, bottom
  background: assets/Borders_and_Logos/250x122_Rounded_Frame_With_Shadow.bmp
stocks:
  stocks:
  symbols:
    - GOOG
    - OKLO
    - AAPL
    - TSLA
  invert_colors: false
  font_size: 20
  background: assets/Borders_and_Logos/250x122_Rounded_Frame_With_Shadow.bmp
  refresh_interval_seconds: 60
weather:
  location: 84043
  units: "F"                 # "F" or "C"
  date_format: "%a %b %d"    # strftime format
  forecast_mode: "daily"    # "hourly" or "daily"
  font_path: fonts/home-video-font/HomeVideo-BLG6G.ttf 
  font_size: 22 #Note that 22 with HomeVideo-BLG6G is what everything has been formatted with!!! Change at your own risk!
  invert_colors: false
  refresh_interval_seconds: 60
  background: assets/Borders_and_Logos/250x122_Rounded_Frame_With_Shadow.bmp
  # background: assets/Borders_and_Logos/250x122_Sqaure_With_Shadow_Background.bmp
  # background: null   # No background
youtube:
  font_path: fonts/home-video-font/HomeVideo-BLG6G.ttf 
  font_size: 22
  timeframe_days: 90
  show_history: true
  show_gain: true
  invert_colors: false
  refresh_interval_seconds: 600
  background: assets/Borders_and_Logos/250x122_Rounded_Frame_With_Shadow.bmp
image:
  path: assets/Borders_and_Logos/250x122_Geometric_Pattern.bmp
  full_scree: true
  # optionally: maybe invert_colors, flip_screen etc.
logging:
  level: DEBUG #"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"

